# Generated by Django 5.0.4 on 2024-04-16 03:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('available_attendee_count', models.IntegerField()),
                ('event_description', models.CharField(max_length=500)),
                ('category', models.CharField(choices=[('CONFERENCE', 'CF'), ('GAME', 'GA'), ('CONCERT', 'CT')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.UUIDField(default=uuid.uuid4)),
                ('space_reserved', models.IntegerField()),
                ('user_name', models.CharField(max_length=255)),
                ('ticket_status', models.CharField(choices=[('CONFIRMED', 'C0'), ('CANCELLED', 'CA'), ('EXPIRED', 'EX')], default='CF', max_length=20)),
            ],
        ),
    ]
